title: WeMade
description: Portfolio
email: hello@wemade.design
url: https://wemade.design
github_username: pauheading

# Server config
livereload : true
include    : [_redirects]
host       : 0.0.0.0

# Build settings
markdown : kramdown
theme    : futuro

collections :
  paul      :
    title   : Paul
    output  : true
  chloe     :
    title   : Chloe
    output  : true
  projects  :
    title   : Projects
    output  : true
  blog      :
    title   : Blog
    output  : true

defaults    :
- scope     :
    path    : ""
  values    :
    layout  : default
- scope     :
    path    : "_projects"
  values    :
    layout  : v2
