title: WeMade
description: Portfolio
email: hello@wemade.design
url: https://wemade.design
github_username: pauheading

# Server config
livereload : true

# Build settings
markdown : kramdown
theme    : barbs

collections :
  about     :
    title   : About
    output  : true
  projects  :
    title   : Projects
    output  : true

defaults    :
- scope     :
    path    : ''
  values    :
    layout  : project
- scope     :
    path    : _about/chloe
  values    :
    chapter : Chloe
- scope     :
    path    : _about/paul
  values    :
    chapter : Paul
