
title: WeMade
description: Portfolio
email: hello@wemade.design
url: https://wemade.design
github_username: pauheading

# Server config
livereload : true

# Build settings
markdown : kramdown
theme    : futuro

exclude :
  - node_modules
  - gulp
  - gulpfile.js

collections :
  paul      :
    title   : Paul
    output  : true
  work      :
    title   : Work
    output  : true
  blog      :
    title   : Blog
    output  : true

defaults   :

- scope    :
    path   : ''
  values   :
    layout : default

- scope    :
    path   : '_work'
  values   :
    type   : work

- scope    :
    path   : '_blog'
  values   :
    type   : blog
    excerpt_separator : <!--more-->
